dist: trusty
sudo: false
language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

jobs:
  include:
    - script: &script
        - bin/xmllint --pattern "*.xlf*,svg" Resources
        - bin/parallel-lint --exclude bin --exclude vendor .
        - bin/phpunit
    - php: 5.6
      script: *script

    - stage: deploy
      script: |
        composer global require clue/phar-composer
        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)

        mkdir -p /tmp/vendors
        pushd /tmp/vendors
        composer require symfony/workflow:^3.3 mpdf/mpdf:^6.1
        phar-composer build .
        popd
        cp /tmp/vendors/vendors.phar .
        ls -l

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
